# Open any file with a fragment in vim, fragments are generated
# by the hyperlink-grep kitten and nothing else so far.
protocol file
fragment_matches [0-9]+
action launch --type=overlay --cwd=current vim +${FRAGMENT} -- ${FILE_PATH}

# Open text files without fragments in the editor
protocol file
mime text/*
action launch --type=overlay --cwd=current -- ${EDITOR} -- ${FILE_PATH}


map ctrl+f launch --type=overlay --stdin-source=@screen_scrollback /bin/sh -c "/usr/local/bin/fzf --no-sort --no-mouse --exact -i --tac | kitty +kitten clipboard"
