#!/bin/sh

while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash -v ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
				wallpaper set -f $(realpath $file) ;;
        "C-p")
                echo "$file" ;;
        esac
done
